// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFleetDevice(arg1) {
  return window['go']['main']['App']['AddFleetDevice'](arg1);
}

export function BackgroundHelperStatus() {
  return window['go']['main']['App']['BackgroundHelperStatus']();
}

export function CheckRuntime() {
  return window['go']['main']['App']['CheckRuntime']();
}

export function CollectService(arg1) {
  return window['go']['main']['App']['CollectService'](arg1);
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function DeployService(arg1, arg2) {
  return window['go']['main']['App']['DeployService'](arg1, arg2);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetCredentials(arg1) {
  return window['go']['main']['App']['GetCredentials'](arg1);
}

export function GetEarningsSummary() {
  return window['go']['main']['App']['GetEarningsSummary']();
}

export function GetFleetState() {
  return window['go']['main']['App']['GetFleetState']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetRuntimeGuides() {
  return window['go']['main']['App']['GetRuntimeGuides']();
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function GetSettingsState() {
  return window['go']['main']['App']['GetSettingsState']();
}

export function InstallBackgroundHelper() {
  return window['go']['main']['App']['InstallBackgroundHelper']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ManagedRuntimePlan() {
  return window['go']['main']['App']['ManagedRuntimePlan']();
}

export function RefreshDeployments() {
  return window['go']['main']['App']['RefreshDeployments']();
}

export function RemoveBackgroundHelper() {
  return window['go']['main']['App']['RemoveBackgroundHelper']();
}

export function RemoveFleetDevice(arg1) {
  return window['go']['main']['App']['RemoveFleetDevice'](arg1);
}

export function RemoveService(arg1) {
  return window['go']['main']['App']['RemoveService'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
