// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';
import {store} from '../models';
import {main} from '../models';
import {catalog} from '../models';

export function CheckRuntime():Promise<runtime.Status>;

export function CollectService(arg1:string):Promise<store.EarningsRecord>;

export function CompleteOnboarding():Promise<void>;

export function DeployService(arg1:string,arg2:Record<string, string>):Promise<store.Deployment>;

export function GetAppState():Promise<main.AppState>;

export function GetCredentials(arg1:string):Promise<Record<string, string>>;

export function GetLogs(arg1:string,arg2:number):Promise<string>;

export function GetRuntimeGuides():Promise<Array<runtime.InstallGuide>>;

export function GetService(arg1:string):Promise<catalog.Service>;

export function ListServices():Promise<Array<catalog.Service>>;

export function ManagedRuntimePlan():Promise<runtime.ManagedRuntimePlan>;

export function RefreshDeployments():Promise<Array<store.Deployment>>;

export function RemoveService(arg1:string):Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function SaveCredentials(arg1:string,arg2:Record<string, string>):Promise<void>;

export function StopService(arg1:string):Promise<void>;
